// ============================================================
// NÚCLEO — Registro de textos editables del sitio (generado).
// Cada clave coincide con un data-copy* del sitio público y con
// una fila de la tabla site_copy.
// type: line = una línea · text = párrafo · block = varios párrafos
//       ("## " título, "- " lista) · list = un ítem por renglón
// ============================================================
window.NUCLEO_COPY_GROUPS = ["Inicio", "Sobre AVA", "Propuesta académica", "Suscripción", "Reseñas", "Contacto", "Privacidad", "Términos y condiciones", "Arrepentimiento y baja", "Menú y pie de página", "Textos generales"];
window.NUCLEO_COPY_FIELDS = [
  {"key": "hero_title", "group": "Inicio", "section": "Portada", "label": "Título principal", "type": "text", "required": true},
  {"key": "hero_subtitle", "group": "Inicio", "section": "Portada", "label": "Bajada", "type": "text"},
  {"key": "home_hero_cta_primary", "group": "Inicio", "section": "Portada", "label": "Botón principal", "type": "line"},
  {"key": "home_hero_cta_secondary", "group": "Inicio", "section": "Portada", "label": "Botón secundario", "type": "line"},
  {"key": "home_hero_note", "group": "Inicio", "section": "Portada", "label": "Nota debajo de los botones", "type": "line"},
  {"key": "home_intro_title", "group": "Inicio", "section": "Qué es AVA", "label": "Título", "type": "text"},
  {"key": "home_intro_body", "group": "Inicio", "section": "Qué es AVA", "label": "Texto", "type": "block"},
  {"key": "home_intro_link", "group": "Inicio", "section": "Qué es AVA", "label": "Link a Sobre AVA", "type": "line"},
  {"key": "home_masters_title", "group": "Inicio", "section": "Másteres", "label": "Título", "type": "line"},
  {"key": "home_masters_subtitle", "group": "Inicio", "section": "Másteres", "label": "Bajada", "type": "line"},
  {"key": "home_method_title", "group": "Inicio", "section": "Metodología", "label": "Título", "type": "text"},
  {"key": "home_method_intro", "group": "Inicio", "section": "Metodología", "label": "Bajada", "type": "text"},
  {"key": "home_method_1_title", "group": "Inicio", "section": "Metodología", "label": "Paso 1 · Título", "type": "line"},
  {"key": "home_method_1_text", "group": "Inicio", "section": "Metodología", "label": "Paso 1 · Texto", "type": "text"},
  {"key": "home_method_2_title", "group": "Inicio", "section": "Metodología", "label": "Paso 2 · Título", "type": "line"},
  {"key": "home_method_2_text", "group": "Inicio", "section": "Metodología", "label": "Paso 2 · Texto", "type": "text"},
  {"key": "home_method_3_title", "group": "Inicio", "section": "Metodología", "label": "Paso 3 · Título", "type": "line"},
  {"key": "home_method_3_text", "group": "Inicio", "section": "Metodología", "label": "Paso 3 · Texto", "type": "text"},
  {"key": "home_method_4_title", "group": "Inicio", "section": "Metodología", "label": "Paso 4 · Título", "type": "line"},
  {"key": "home_method_4_text", "group": "Inicio", "section": "Metodología", "label": "Paso 4 · Texto", "type": "text"},
  {"key": "home_community_title", "group": "Inicio", "section": "Comunidad", "label": "Título", "type": "text"},
  {"key": "community_body", "group": "Inicio", "section": "Comunidad", "label": "Texto", "type": "block"},
  {"key": "home_reviews_title", "group": "Inicio", "section": "Reseñas", "label": "Título (solo se ve si hay reseñas aprobadas)", "type": "line"},
  {"key": "home_reviews_link", "group": "Inicio", "section": "Reseñas", "label": "Link a todas las reseñas", "type": "line"},
  {"key": "home_early_title", "group": "Inicio", "section": "Primera generación", "label": "Título", "type": "text"},
  {"key": "home_early_text", "group": "Inicio", "section": "Primera generación", "label": "Texto", "type": "text"},
  {"key": "home_early_cta", "group": "Inicio", "section": "Primera generación", "label": "Botón", "type": "line"},
  {"key": "home_final_title", "group": "Inicio", "section": "Cierre", "label": "Título", "type": "line"},
  {"key": "home_final_cta_primary", "group": "Inicio", "section": "Cierre", "label": "Botón principal", "type": "line"},
  {"key": "home_final_cta_secondary", "group": "Inicio", "section": "Cierre", "label": "Botón secundario", "type": "line"},
  {"key": "about_hero_title", "group": "Sobre AVA", "section": "Portada", "label": "Título principal", "type": "text", "required": true},
  {"key": "about_title", "group": "Sobre AVA", "section": "Por qué existe AVA", "label": "Título", "type": "line"},
  {"key": "about_body", "group": "Sobre AVA", "section": "Por qué existe AVA", "label": "Texto", "type": "block"},
  {"key": "founder_section_title", "group": "Sobre AVA", "section": "Fundadora", "label": "Título de la sección", "type": "line"},
  {"key": "founder_name", "group": "Sobre AVA", "section": "Fundadora", "label": "Nombre", "type": "line"},
  {"key": "founder_role", "group": "Sobre AVA", "section": "Fundadora", "label": "Rol y ubicación", "type": "line"},
  {"key": "founder_bio_body", "group": "Sobre AVA", "section": "Fundadora", "label": "Biografía", "type": "block"},
  {"key": "founder_books", "group": "Sobre AVA", "section": "Fundadora", "label": "Publicaciones (renglones con \"- \" = lista; *texto* = cursiva)", "type": "block"},
  {"key": "founder_note", "group": "Sobre AVA", "section": "Fundadora", "label": "Nota final", "type": "text"},
  {"key": "about_final_title", "group": "Sobre AVA", "section": "Cierre", "label": "Título", "type": "line"},
  {"key": "about_final_cta_primary", "group": "Sobre AVA", "section": "Cierre", "label": "Botón principal", "type": "line"},
  {"key": "about_final_cta_secondary", "group": "Sobre AVA", "section": "Cierre", "label": "Botón secundario", "type": "line"},
  {"key": "program_hero_title", "group": "Propuesta académica", "section": "Portada", "label": "Título principal ({Cantidad} = cantidad de Másteres)", "type": "text", "required": true},
  {"key": "program_hero_text", "group": "Propuesta académica", "section": "Portada", "label": "Bajada", "type": "text"},
  {"key": "program_gifts_title", "group": "Propuesta académica", "section": "Cursos de regalo", "label": "Título", "type": "text"},
  {"key": "program_gifts_text", "group": "Propuesta académica", "section": "Cursos de regalo", "label": "Texto", "type": "text"},
  {"key": "program_method_title", "group": "Propuesta académica", "section": "Principios", "label": "Título", "type": "text"},
  {"key": "program_method_1_title", "group": "Propuesta académica", "section": "Principios", "label": "Principio 1 · Título", "type": "line"},
  {"key": "program_method_1_text", "group": "Propuesta académica", "section": "Principios", "label": "Principio 1 · Texto", "type": "text"},
  {"key": "program_method_2_title", "group": "Propuesta académica", "section": "Principios", "label": "Principio 2 · Título", "type": "line"},
  {"key": "program_method_2_text", "group": "Propuesta académica", "section": "Principios", "label": "Principio 2 · Texto", "type": "text"},
  {"key": "program_cert_title", "group": "Propuesta académica", "section": "Certificación", "label": "Título", "type": "line"},
  {"key": "program_cert_text", "group": "Propuesta académica", "section": "Certificación", "label": "Texto", "type": "text"},
  {"key": "program_cert_card_title", "group": "Propuesta académica", "section": "Certificación", "label": "Recuadro · Título", "type": "line"},
  {"key": "program_cert_card_text", "group": "Propuesta académica", "section": "Certificación", "label": "Recuadro · Texto", "type": "text"},
  {"key": "program_final_title", "group": "Propuesta académica", "section": "Cierre", "label": "Título", "type": "line"},
  {"key": "program_final_cta", "group": "Propuesta académica", "section": "Cierre", "label": "Botón", "type": "line"},
  {"key": "plan_hero_title", "group": "Suscripción", "section": "Portada", "label": "Título principal", "type": "line", "required": true},
  {"key": "plan_gifts_label", "group": "Suscripción", "section": "Desglose de precios", "label": "Fila de cursos de regalo", "type": "line"},
  {"key": "plan_gifts_value", "group": "Suscripción", "section": "Desglose de precios", "label": "Valor de la fila de regalo", "type": "line"},
  {"key": "plan_total_label", "group": "Suscripción", "section": "Desglose de precios", "label": "Fila del total por separado", "type": "line"},
  {"key": "plan_regular_label", "group": "Suscripción", "section": "Desglose de precios", "label": "Fila del precio anual", "type": "line"},
  {"key": "plan_promo_label", "group": "Suscripción", "section": "Desglose de precios", "label": "Fila del precio promocional", "type": "line"},
  {"key": "plan_tag_promo", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Etiqueta con promoción activa", "type": "line"},
  {"key": "plan_tag", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Etiqueta sin promoción", "type": "line"},
  {"key": "plan_price_suffix", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Texto al lado del precio", "type": "line"},
  {"key": "plan_text", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Texto", "type": "text"},
  {"key": "plan_cta", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Botón", "type": "line"},
  {"key": "plan_guarantee_note", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Nota de garantía ({garantia} = días de Precios)", "type": "line"},
  {"key": "plan_features", "group": "Suscripción", "section": "Tarjeta del plan", "label": "Beneficios (uno por renglón; {cantidad} = cantidad de Másteres)", "type": "list", "required": true},
  {"key": "waitlist_title", "group": "Suscripción", "section": "Lista de espera", "label": "Título", "type": "line"},
  {"key": "waitlist_intro", "group": "Suscripción", "section": "Lista de espera", "label": "Texto", "type": "text"},
  {"key": "waitlist_submit", "group": "Suscripción", "section": "Lista de espera", "label": "Botón del formulario", "type": "line", "required": true},
  {"key": "waitlist_done_title", "group": "Suscripción", "section": "Lista de espera", "label": "Confirmación · Título", "type": "line"},
  {"key": "waitlist_done_text", "group": "Suscripción", "section": "Lista de espera", "label": "Confirmación · Texto", "type": "text"},
  {"key": "waitlist_done_link", "group": "Suscripción", "section": "Lista de espera", "label": "Confirmación · Link", "type": "line"},
  {"key": "faq_title", "group": "Suscripción", "section": "Preguntas frecuentes", "label": "Título (las preguntas se editan en FAQ)", "type": "line"},
  {"key": "form_label_last_name", "group": "Suscripción", "section": "Lista de espera", "label": "Campo apellido", "type": "line", "required": true},
  {"key": "form_label_country", "group": "Suscripción", "section": "Lista de espera", "label": "Campo país", "type": "line", "required": true},
  {"key": "form_label_phone", "group": "Suscripción", "section": "Lista de espera", "label": "Campo teléfono", "type": "line", "required": true},
  {"key": "plan_per_year", "group": "Suscripción", "section": "Desglose de precios", "label": "Texto después de cada precio", "type": "line"},
  {"key": "form_placeholder_country", "group": "Suscripción", "section": "Lista de espera", "label": "Ejemplo dentro del campo país", "type": "line"},
  {"key": "form_placeholder_phone", "group": "Suscripción", "section": "Lista de espera", "label": "Ejemplo dentro del campo teléfono", "type": "line"},
  {"key": "waitlist_error_connection", "group": "Suscripción", "section": "Lista de espera", "label": "Error: sin conexión", "type": "text"},
  {"key": "waitlist_error_send", "group": "Suscripción", "section": "Lista de espera", "label": "Error: no se pudo guardar", "type": "text"},
  {"key": "reviews_hero_title", "group": "Reseñas", "section": "Portada", "label": "Título principal", "type": "line", "required": true},
  {"key": "reviews_empty", "group": "Reseñas", "section": "Portada", "label": "Aviso cuando todavía no hay reseñas", "type": "text"},
  {"key": "reviews_form_title", "group": "Reseñas", "section": "Formulario", "label": "Título", "type": "line"},
  {"key": "reviews_form_text", "group": "Reseñas", "section": "Formulario", "label": "Texto", "type": "text"},
  {"key": "reviews_label_name", "group": "Reseñas", "section": "Formulario", "label": "Campo nombre", "type": "line", "required": true},
  {"key": "reviews_label_text", "group": "Reseñas", "section": "Formulario", "label": "Campo reseña", "type": "line", "required": true},
  {"key": "reviews_label_masters", "group": "Reseñas", "section": "Formulario", "label": "Campo Másteres", "type": "line", "required": true},
  {"key": "reviews_submit", "group": "Reseñas", "section": "Formulario", "label": "Botón", "type": "line", "required": true},
  {"key": "reviews_success", "group": "Reseñas", "section": "Formulario", "label": "Mensaje de envío correcto", "type": "text"},
  {"key": "reviews_error_connection", "group": "Reseñas", "section": "Formulario", "label": "Error: sin conexión", "type": "text"},
  {"key": "reviews_error_send", "group": "Reseñas", "section": "Formulario", "label": "Error: no se pudo guardar", "type": "text"},
  {"key": "contact_hero_title", "group": "Contacto", "section": "Portada", "label": "Título principal", "type": "line", "required": true},
  {"key": "contact_hero_text", "group": "Contacto", "section": "Portada", "label": "Bajada", "type": "text"},
  {"key": "contact_label_reason", "group": "Contacto", "section": "Formulario", "label": "Campo motivo", "type": "line", "required": true},
  {"key": "contact_reasons", "group": "Contacto", "section": "Formulario", "label": "Motivos (uno por renglón)", "type": "list", "required": true},
  {"key": "contact_label_message", "group": "Contacto", "section": "Formulario", "label": "Campo mensaje", "type": "line", "required": true},
  {"key": "contact_submit", "group": "Contacto", "section": "Formulario", "label": "Botón", "type": "line", "required": true},
  {"key": "contact_success", "group": "Contacto", "section": "Formulario", "label": "Mensaje de envío correcto", "type": "text"},
  {"key": "contact_whatsapp_title", "group": "Contacto", "section": "Datos de contacto", "label": "Título WhatsApp", "type": "line"},
  {"key": "contact_email_title", "group": "Contacto", "section": "Datos de contacto", "label": "Título Email", "type": "line"},
  {"key": "contact_social_title", "group": "Contacto", "section": "Datos de contacto", "label": "Título Redes", "type": "line"},
  {"key": "contact_hours_title", "group": "Contacto", "section": "Datos de contacto", "label": "Título del horario de atención", "type": "line"},
  {"key": "contact_hours", "group": "Contacto", "section": "Datos de contacto", "label": "Horario de atención (vacío = no se muestra)", "type": "text"},
  {"key": "form_label_name", "group": "Contacto", "section": "Formulario", "label": "Campo nombre (también en la lista de espera)", "type": "line", "required": true, "where": "Contacto, Suscripción"},
  {"key": "form_label_email", "group": "Contacto", "section": "Formulario", "label": "Campo email (también en la lista de espera)", "type": "line", "required": true, "where": "Contacto, Suscripción"},
  {"key": "contact_error_connection", "group": "Contacto", "section": "Formulario", "label": "Error: sin conexión", "type": "text"},
  {"key": "contact_error_send", "group": "Contacto", "section": "Formulario", "label": "Error: no se pudo guardar", "type": "text"},
  {"key": "privacy_hero_title", "group": "Privacidad", "section": "Portada", "label": "Título principal", "type": "line", "required": true},
  {"key": "privacidad_body", "group": "Privacidad", "section": "Contenido", "label": "Texto completo (\"## \" = título de sección)", "type": "block"},
  {"key": "privacy_owner_title", "group": "Privacidad", "section": "Quién es responsable de tus datos", "label": "Título de la sección", "type": "line"},
  {"key": "terms_hero_title", "group": "Términos y condiciones", "section": "Portada", "label": "Título principal", "type": "line", "required": true},
  {"key": "provider_title", "group": "Términos y condiciones", "section": "Quién presta el servicio", "label": "Título de la sección", "type": "line"},
  {"key": "provider_name", "group": "Términos y condiciones", "section": "Quién presta el servicio", "label": "Nombre de quien presta el servicio (también en Privacidad; vacío = se oculta la sección)", "type": "text", "where": "Términos y condiciones, Privacidad"},
  {"key": "provider_cuit", "group": "Términos y condiciones", "section": "Quién presta el servicio", "label": "CUIT, en una línea completa (ej.: CUIT: 27-12345678-9). Vacío = no se muestra", "type": "line", "where": "Términos y condiciones, Privacidad"},
  {"key": "provider_address", "group": "Términos y condiciones", "section": "Quién presta el servicio", "label": "Domicilio para notificaciones, en una línea completa (ej.: Domicilio: …). No tiene que ser tu casa. Vacío = no se muestra", "type": "line", "where": "Términos y condiciones, Privacidad"},
  {"key": "provider_email_label", "group": "Términos y condiciones", "section": "Quién presta el servicio", "label": "Texto antes del email principal", "type": "line", "where": "Términos y condiciones, Privacidad"},
  {"key": "terminos_body", "group": "Términos y condiciones", "section": "Contenido", "label": "Texto completo (\"## \" = título de sección; {garantia} = días de Precios)", "type": "block"},
  {"key": "request_privacy_note", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Aviso sobre los datos (sin casilla: la ley no permite sumar requisitos)", "type": "text", "where": "Arrepentimiento, Baja"},
  {"key": "withdrawal_link", "group": "Arrepentimiento y baja", "section": "Links (arriba de todo y en el pie)", "label": "Link al botón de arrepentimiento (nombre exigido por la Disposición 954/2025)", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "cancel_link", "group": "Arrepentimiento y baja", "section": "Links (arriba de todo y en el pie)", "label": "Link al botón de baja (nombre exigido por la Disposición 954/2025)", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "withdrawal_title", "group": "Arrepentimiento y baja", "section": "Página de arrepentimiento", "label": "Título", "type": "line", "required": true},
  {"key": "withdrawal_text", "group": "Arrepentimiento y baja", "section": "Página de arrepentimiento", "label": "Texto", "type": "block"},
  {"key": "withdrawal_submit", "group": "Arrepentimiento y baja", "section": "Página de arrepentimiento", "label": "Botón del formulario", "type": "line", "required": true},
  {"key": "withdrawal_done_title", "group": "Arrepentimiento y baja", "section": "Página de arrepentimiento", "label": "Confirmación · Título", "type": "line"},
  {"key": "cancel_title", "group": "Arrepentimiento y baja", "section": "Página de baja", "label": "Título", "type": "line", "required": true},
  {"key": "cancel_text", "group": "Arrepentimiento y baja", "section": "Página de baja", "label": "Texto", "type": "block"},
  {"key": "cancel_submit", "group": "Arrepentimiento y baja", "section": "Página de baja", "label": "Botón del formulario", "type": "line", "required": true},
  {"key": "cancel_done_title", "group": "Arrepentimiento y baja", "section": "Página de baja", "label": "Confirmación · Título", "type": "line"},
  {"key": "request_label_email", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Campo email", "type": "line", "required": true, "where": "Arrepentimiento, Baja"},
  {"key": "request_label_operation", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Campo número de operación", "type": "line", "required": true, "where": "Arrepentimiento, Baja"},
  {"key": "request_label_comment", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Campo comentario", "type": "line", "required": true, "where": "Arrepentimiento, Baja"},
  {"key": "request_code_label", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Confirmación · Texto sobre el código", "type": "line", "where": "Arrepentimiento, Baja"},
  {"key": "request_done_text", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Confirmación · Texto", "type": "text", "where": "Arrepentimiento, Baja"},
  {"key": "request_copy_button", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Confirmación · Botón copiar", "type": "line", "required": true, "where": "Arrepentimiento, Baja"},
  {"key": "request_done_link", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Confirmación · Link", "type": "line", "where": "Arrepentimiento, Baja"},
  {"key": "request_copied", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Aviso al copiar el código", "type": "line"},
  {"key": "request_error_connection", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Error: sin conexión", "type": "text"},
  {"key": "request_error_send", "group": "Arrepentimiento y baja", "section": "Formulario (las dos páginas)", "label": "Error: no se pudo guardar", "type": "text"},
  {"key": "nav_home", "group": "Menú y pie de página", "section": "Menú", "label": "Inicio", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_about", "group": "Menú y pie de página", "section": "Menú", "label": "Sobre AVA", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_program", "group": "Menú y pie de página", "section": "Menú", "label": "Propuesta académica", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_plan", "group": "Menú y pie de página", "section": "Menú", "label": "Suscripción", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_reviews", "group": "Menú y pie de página", "section": "Menú", "label": "Reseñas", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_contact", "group": "Menú y pie de página", "section": "Menú", "label": "Contacto", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_campus", "group": "Menú y pie de página", "section": "Menú", "label": "Botón del Campus", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "nav_cta", "group": "Menú y pie de página", "section": "Menú", "label": "Botón principal del menú", "type": "line", "required": true, "where": "Todas las páginas"},
  {"key": "footer_tagline", "group": "Menú y pie de página", "section": "Pie de página", "label": "Texto de la marca", "type": "text", "where": "Todas las páginas"},
  {"key": "footer_col_academy", "group": "Menú y pie de página", "section": "Pie de página", "label": "Título de la columna 1", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_col_help", "group": "Menú y pie de página", "section": "Pie de página", "label": "Título de la columna 2", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_col_social", "group": "Menú y pie de página", "section": "Pie de página", "label": "Título de la columna de redes", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_privacy", "group": "Menú y pie de página", "section": "Pie de página", "label": "Link a Privacidad", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_terms", "group": "Menú y pie de página", "section": "Pie de página", "label": "Link a Términos", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_rights", "group": "Menú y pie de página", "section": "Pie de página", "label": "Derechos (usá {anio} para el año)", "type": "line", "where": "Todas las páginas"},
  {"key": "footer_location", "group": "Menú y pie de página", "section": "Pie de página", "label": "Ubicación", "type": "line", "where": "Todas las páginas"},
  {"key": "legal_footer", "group": "Menú y pie de página", "section": "Pie de página", "label": "Leyenda legal (Ley 25.326)", "type": "text", "where": "Todas las páginas"},
  {"key": "consent_label", "group": "Textos generales", "section": "Formularios", "label": "Casilla de la Política de privacidad (contacto, lista de espera y reseñas)", "type": "text", "required": true, "where": "Contacto, Suscripción, Reseñas"},
  {"key": "consent_link", "group": "Textos generales", "section": "Formularios", "label": "Link a la Política de privacidad (al lado de la casilla y del aviso)", "type": "line", "required": true, "where": "Contacto, Suscripción, Reseñas, Arrepentimiento, Baja"},
  {"key": "publish_consent_label", "group": "Suscripción", "section": "Lista de espera", "label": "Casilla opcional: autorización para publicar el nombre si gana una beca", "type": "text", "required": true},
  {"key": "form_sending", "group": "Textos generales", "section": "Formularios", "label": "Botón mientras se envía", "type": "line", "required": true},
  {"key": "campus_url", "group": "Textos generales", "section": "Campus", "label": "Link del Campus (vacío = todavía no abrió)", "type": "line"},
  {"key": "campus_closed", "group": "Textos generales", "section": "Campus", "label": "Aviso mientras el Campus no abrió", "type": "text"},
  {"key": "whatsapp_float_label", "group": "Textos generales", "section": "WhatsApp", "label": "Descripción del botón flotante (para lectores de pantalla)", "type": "line"},
  {"key": "notfound_text", "group": "Textos generales", "section": "Página no encontrada (404)", "label": "Texto", "type": "text"},
  {"key": "notfound_cta", "group": "Textos generales", "section": "Página no encontrada (404)", "label": "Botón", "type": "line"}
];
